FROM python:3.14-slim-trixie
COPY --from=ghcr.io/astral-sh/uv:0.9 /uv /bin/uv
COPY requirements_dev.txt /requirements_dev.txt
RUN uv pip install --system --no-cache-dir -r /requirements_dev.txt
COPY pptx2txt.py /pptx2txt.py
WORKDIR /work
ENV HOME=/tmp
ARG SOURCE_COMMIT
ENV SOURCE_COMMIT=$SOURCE_COMMIT
CMD ["/bin/bash"]
