#!/bin/bash
set -eu -o pipefail

if [[ $(command -v docker) ]]; then
  docker container run \
    --name pptx2txt$$ \
    --rm \
    -t \
    -u "$(id -u):$(id -g)" \
    -v "$PWD":/work \
    ghcr.io/shakiyam/pptx2txt "$@"
else
  podman container run \
    --name pptx2txt$$ \
    --rm \
    --security-opt label=disable \
    -t \
    -v "$PWD":/work \
    ghcr.io/shakiyam/pptx2txt "$@"
fi
