#!/bin/bash
set -Eeu -o pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
readonly SCRIPT_DIR

if command -v docker &>/dev/null; then
  docker container run \
    --name "pptx2txt_dev_$(uuidgen | head -c8)" \
    --rm \
    -it \
    -u "$(id -u):$(id -g)" \
    -v "$PWD":/work \
    -v "$SCRIPT_DIR"/pptx2txt.py:/pptx2txt.py \
    ghcr.io/shakiyam/pptx2txt_dev "$@"
else
  podman container run \
    --name "pptx2txt_dev_$(uuidgen | head -c8)" \
    --rm \
    --security-opt label=disable \
    -it \
    -v "$PWD":/work \
    -v "$SCRIPT_DIR"/pptx2txt.py:/pptx2txt.py \
    ghcr.io/shakiyam/pptx2txt_dev "$@"
fi
