#!/bin/bash
set -eu -o pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
readonly SCRIPT_DIR

if [[ $(command -v docker) ]]; then
  docker container run \
    --name pptx2txt_dev$$ \
    --rm \
    -it \
    -u "$(id -u):$(id -g)" \
    -v "$PWD":/work \
    -v "$SCRIPT_DIR"/pptx2txt.py:/pptx2txt.py \
    docker.io/shakiyam/pptx2txt_dev "$@"
else
  podman container run \
    --name pptx2txt_dev$$ \
    --rm \
    --security-opt label=disable \
    -it \
    -v "$PWD":/work \
    -v "$SCRIPT_DIR"/pptx2txt.py:/pptx2txt.py \
    docker.io/shakiyam/pptx2txt_dev "$@"
fi
