#!/bin/bash
set -Eeu -o pipefail

if command -v docker &>/dev/null; then
  docker container run \
    --name "pptx2txt_$(uuidgen | head -c8)" \
    --rm \
    -t \
    -u "$(id -u):$(id -g)" \
    -v "$PWD":/work \
    ghcr.io/shakiyam/pptx2txt "$@"
else
  podman container run \
    --name "pptx2txt_$(uuidgen | head -c8)" \
    --rm \
    --security-opt label=disable \
    -t \
    -v "$PWD":/work \
    ghcr.io/shakiyam/pptx2txt "$@"
fi
