name: CI
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Run make format
        run: make format
      - name: Run check_for_file_updates.sh
        run: ./tools/check_for_file_updates.sh
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Run make --keep-going lint
        run: make --keep-going lint
        env:
          GH_TOKEN: ${{ github.token }}
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Run make mypy
        run: make mypy
  pip_licenses:
    name: pip-licenses
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Run make pip_licenses
        run: make pip_licenses
  test:
    name: Test the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Run make test
        run: make test
  trivy:
    name: Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Run make trivy
        run: make trivy
  build:
    name: Build and Push
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    needs: [format, lint, mypy, pip_licenses, test, trivy]
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          build-args: SOURCE_COMMIT=${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/shakiyam/pptx2txt:latest
